### ISSUE TITLE
JDK 11 Compatibility

### ISSUE THREAD

**Issue by hamiltml** [AllTheDucks/jshack#77]
Blackboard will be updating its back-end Java libraries to JDK 11 Corretto in November 2019. Is this building block currently compatible? If it is not, will there be a compatible version?

Thank You,
Megan

**Comment by shaneargo** [comment]
Hi Megan,

This is an experimental v2 of jshack. I've recreated your issue in the v1 project.

https://github.com/AllTheDucks/jshack-v1/issues/7

Cheers,
Shane.
