### ISSUE TITLE
Permission issue in BB SaaS

### ISSUE THREAD

**Issue by scollovati** [AllTheDucks/jshack#78]
As you may know, in SaaS by default the system tool is not visible because the entitlment is missing from the admin role permissions.

I think that the issue is here:
https://github.com/AllTheDucks/jshack/blob/6a860cfa088a390c802efce0c099501cf81dceba/b2/src/main/webapp/WEB-INF/bb-manifest.xml#L54

Probably, this is caused by one or both of the following settings:
-  `<type value="nav_handle_param" />` rather than  `<type value="system_tool"/>`
-  `<entitlement-uid value="system.jshacks.CREATE" />` rather than something like `<entitlement-uid value="alltheducks.jshacks.CREATE"/>`

**Comment by shaneargo** [comment]
Hi @scollovati,

This project is an experimental (and somewhat dead) version 2 of JS Hack.

Can you please resubmit the issue on the JS Hack v1 project?:
https://github.com/AllTheDucks/jshack-v1

Cheers,
Shane.
